---
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/azzmosphere/pluralsight-spring-cloudconfig-wa-tolls
          #username: uname
          #password: pass